### ISSUE TITLE
error: cannot read property 'close' of null

### ISSUE THREAD

**Issue by KutnerUri** [Tofandel/prerender-spa-plugin-next#12]
getting this error during build:
```
Error: Cannot read property 'close' of null
    at Server.destroy (/Users/kutner/projects/bit-bin/node_modules/@prerenderer/prerenderer/es6/server.js:46:24)
    at Prerenderer.destroy (/Users/kutner/projects/bit-bin/node_modules/@prerenderer/prerenderer/es6/index.js:88:18)
    at PrerenderSPAPlugin.prerender (/Users/kutner/projects/bit-bin/node_modules/prerender-spa-plugin-next/dist/index.js:129:25)
```

seems like it is coming from this code:
https://github.com/JoshTheDerf/prerenderer/blob/7d33c93984118c3f5c1a6f65e9f14a34eadf2357/es6/server.js#L50
``` ts
destroy () {
  this._nativeServer.close()
}
```
which is the express server serving the static files? any idea why it is happening?

Sometimes I get this error:
```
Error: Cannot read property 'close' of null
    at PuppeteerRenderer.destroy (/Users/kutner/projects/bit-bin/node_modules/@prerenderer/renderer-puppeteer/es6/renderer.js:140:21)
    at Prerenderer.destroy (/Users/kutner/projects/bit-bin/node_modules/@prerenderer/prerenderer/es6/index.js:87:20)
    at PrerenderSPAPlugin.prerender (/Users/kutner/projects/bit-bin/node_modules/prerender-spa-plugin-next/dist/index.js:129:25)
```
which is coming from puppeteer, which is related to https://github.com/puppeteer/puppeteer/issues/4197 and was probably fixed by https://github.com/puppeteer/puppeteer/pull/4276

**Comment by KutnerUri** [comment]
Found it - I defined a `server.proxy` without the `target` option, and the initialization code at `./server` did not catch the error, silently crushing the plugin.
Maybe we need a try catch on the entire `.initialize()` method?

**Comment by Tofandel** [comment]
I have finally released a full suite upgrade, the plugin is now available under [`@prerenderer/webpack-plugin`](https://github.com/JoshTheDerf/prerenderer) which also has a fix for this issue and many more

I'm deprecating this package and archiving the repo
